server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT}
  requestLog:
    appenders:
      - type: console

logging:
  appenders:
    - type: console
      logFormat: "%-5level [%d] %X{correlationId:-0} %logger{5}: %msg%n"
